### ISSUE TITLE
InvalidArgumentError

### ISSUE THREAD

**Issue by 980202006** [sander-wood/autoharmonizer#2]
Hello, I encountered an error, as follows:
The input_chord_left is array([[14, 14, 14, 14, 15, 14, 14, 14, 14]], dtype=int32)
"""
2022-03-09 11:28:57.595376: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2022-03-09 11:28:57.623071: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-03-09 11:28:57.623404: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce RTX 3060 computeCapability: 8.6
coreClock: 1.852GHz coreCount: 28 deviceMemorySize: 11.76GiB deviceMemoryBandwidth: 335.32GiB/s
2022-03-09 11:28:57.623423: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2022-03-09 11:28:57.625232: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
2022-03-09 11:28:57.625266: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublasLt.so.11
2022-03-09 11:28:57.625994: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcufft.so.10
2022-03-09 11:28:57.626158: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcurand.so.10
2022-03-09 11:28:57.626239: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory
2022-03-09 11:28:57.626631: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusparse.so.11
2022-03-09 11:28:57.626727: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudnn.so.8
2022-03-09 11:28:57.626737: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1766] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2022-03-09 11:28:57.627027: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-03-09 11:28:57.627332: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2022-03-09 11:28:57.627340: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      
  0%|          | 0/1 [00:00<?, ?it/s]2022-03-09 11:29:12.128660: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2022-03-09 11:29:12.147969: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2899885000 Hz
  0%|          | 0/1 [01:13<?, ?it/s]
Traceback (most recent call last):
  File "/home/aaa/anaconda3/envs/kerasss/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/aaa/anaconda3/envs/kerasss/lib/python3.7/site-packages/tensorflow/python/ops/variable_scope.py", line 2833, in variable_creator_scope
    yield
  File "/home/aaa/anaconda3/envs/kerasss/lib/python3.7/site-packages/keras/engine/training.py", line 1702, in predict
    tmp_batch_outputs = self.predict_function(iterator)
  File "/home/aaa/anaconda3/envs/kerasss/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 889, in __call__
    result = self._call(*args, **kwds)
  File "/home/aaa/anaconda3/envs/kerasss/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 957, in _call
    filtered_flat_args, self._concrete_stateful_fn.captured_inputs)  # pylint: disable=protected-access
  File "/home/aaa/anaconda3/envs/kerasss/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1961, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/aaa/anaconda3/envs/kerasss/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 596, in call
    ctx=ctx)
  File "/home/aaa/anaconda3/envs/kerasss/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError:  indices[0,4] = 15 is not in [0, 15)
	 [[node model_1/embeded_chord_left/embedding_lookup (defined at home/aaa/anaconda3/envs/kerasss/lib/python3.7/site-packages/keras/layers/embeddings.py:184) ]] [Op:__inference_predict_function_99639]
Errors may have originated from an input operation.
Input Source operations connected to node model_1/embeded_chord_left/embedding_lookup:
 model_1/embeded_chord_left/embedding_lookup/79737 (defined at home/aaa/anaconda3/envs/kerasss/lib/python3.7/contextlib.py:112)	
 model_1/embeded_chord_left/Cast (defined at home/aaa/anaconda3/envs/kerasss/lib/python3.7/site-packages/keras/layers/embeddings.py:183)
Function call stack:
predict_function
python-BaseException
input_chord_left
Python 3.7.10 (default, Jun  4 2021, 14:48:32) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.28.0 -- An enhanced Interactive Python. Type '?' for help.
PyDev console: using IPython 7.28.0
"""

**Comment by sander-wood** [comment]
Did you change the code before you encountered this problem?

**Comment by 980202006** [comment]
No, I use the code clone from the master branch.

**Comment by sander-wood** [comment]
Then, are you sure that all the dependencies are the same as mine (please check `README`)?

**Comment by 980202006** [comment]
Yes. I used the same python and package version. I noticed that the input_dim=15 of the embedding layer of chord_model, mul_seg(chord_segs,i,segments_length,'left',15) will add 15 as a separator, resulting in out of embedding, is this the problem?

**Comment by sander-wood** [comment]
It may be that I forgot that I should keep the mask zero in as one dimension. But I can run the code properly. If you are sure that all the dependencies are the same as mine, please change the code `input_dim=15' to `input_dim=16' on line 176 and run `chord_model.py` to retrain the model.

**Comment by 980202006** [comment]
Thank you!

**Comment by 980202006** [comment]
Traceback (most recent call last):
  File "/media/aaa/code2/autoharmonizer/harmonizer.py", line 431, in <module>
    chord_model = build_chord_model(SEGMENTS_LENGTH, CHO_RNN_SIZE, CHO_NUM_LAYERS, 'chord_'+WEIGHTS_PATH)
  File "/media/aaa/code2/autoharmonizer/chord_model.py", line 268, in build_chord_model
    model.load_weights(weights_path)
  File "/home/aaa/anaconda3/envs/kerasss/lib/python3.7/site-packages/keras/engine/saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "/home/aaa/anaconda3/envs/kerasss/lib/python3.7/site-packages/keras/engine/network.py", line 1230, in load_weights
    f, self.layers, reshape=reshape)
  File "/home/aaa/anaconda3/envs/kerasss/lib/python3.7/site-packages/keras/engine/saving.py", line 1234, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "/home/aaa/anaconda3/envs/kerasss/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 2960, in batch_set_value
    tf_keras_backend.batch_set_value(tuples)
  File "/home/aaa/anaconda3/envs/kerasss/lib/python3.7/site-packages/tensorflow/python/keras/backend.py", line 3384, in batch_set_value
    x.assign(np.asarray(value, dtype=dtype(x)))
  File "/home/aaa/anaconda3/envs/kerasss/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 846, in assign
    self._shape.assert_is_compatible_with(value_tensor.shape)
  File "/home/aaa/anaconda3/envs/kerasss/lib/python3.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 1117, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (16, 4) and (15, 4) are incompatible

**Comment by sander-wood** [comment]
Have you retrained the model?

**Comment by 980202006** [comment]
I did not retrain the model

**Comment by sander-wood** [comment]
It will work fine if you do not want to retrain the model, but you need to make sure the model is running on the GPU and not the CPU. I now confirm that the issue you mention occurs when using the CPU. However, if you run it on a GPU, you won't get this error reported.
