### ISSUE TITLE
Error when Harmonization: from keras.utils import Sequence

### ISSUE THREAD

**Issue by MaximeHoude** [sander-wood/autoharmonizer#3]
Hi Shangda,

I had no problem playing with your Chord_generation, but I have the following issue when I try to `harmonizer.py`:

```
(autohar) C:\code\autoharmonizer>py harmonizer.py
Traceback (most recent call last):
  File "C:\code\autoharmonizer\harmonizer.py", line 9, in <module>
    from model import build_model
  File "C:\code\autoharmonizer\model.py", line 9, in <module>
    from keras.utils import Sequence
ImportError: cannot import name 'Sequence' from 'keras.utils' (C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\__init__.py)
```

I'm on Windows 10 (with Cuda) and I'm running a Conda Environment with all your Dependencies. I'm not interested to train, simply for Melody Harmonization.

Thanks!

**Comment by sander-wood** [comment]
I apologize for the delay in responding to your issue. I recommend that you uninstall your current version of Keras and then install version 2.3.0 by running the following commands: 
```
pip uninstall keras
pip install keras==2.3.0
```

Please let me know if you have any further questions or concerns.
